= Minutes from Meeting 05 (December 11th, 2025): Common DNS Admin API
:doctype: article
:keywords: Common DNS Admin API
:author: Patrick Ben Koetter
:email: p@sys4.de
:subject: Kickoff-Meeting
:revnumber: 0.2
:revdate: 2025-12-19
:status: draft
:copyright: (C) sys4 AG
:publisher: sys4 AG
:lang: en
:hyphens: en
:encoding: UTF-8
:pdf-version: 1.7
:toc:
:toclevels: 3
:sectnums:
:pagenums:
:icons: image
:iconsdir: /etc/sys4/corporatedesign/icons
:title-page:
:source-highlighter: rouge
:rouge-style: base16
:pdf-theme: /etc/sys4/corporatedesign/sys4.yml
:pdf-fontsdir: /etc/sys4/corporatedesign/fonts
:asciidoctor-diagram:


== API questions

Carsten had a list of open questions regarding the API which we discussed during
the meeting. We spent most of the time discussing if the API should be friendly
to bulk operations and agreed we don't have to answer this at the moment as this
would be some kind of "scope creep" (Petr) regarding our main goal in this
iteration to come up with an API that does what NSUPDATE does.

Here are the notes Carsten took during our discussion:

----
 * API Bulk friendliness
   - bulk operation only inside single zone -> line NSUPDATE
   - every operation should be possible in bulk -> later, but should be
     considered
   - streaming API? -> later
 * Domain Name Encoding
   - punycode?
 * RRType as numbers in addition to string representation
 * Should the API commands be atomic?
   - atomic updates are desired
 * Should the API be synchronous?
   - API controlled jobs? -> better to do preprequisites
   - lock only on write API commands
   - or NSUPDATE like prerequisites?
   - synchronicity up to the first "primary database"
   - synchronicity select-able via the API (field)
   - https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/202
   - https://www.jsonrpc.org/specification

 * API desired outcome logic
   - void operation should be treated as success (maybe with special
     return code that indicates void operation)
      #+begin_quote
   if API shall consider "desired" outcome logic, or consider a void
   operation an error? Example: is DELETE of RR that does not exist an
   error or success? Outcome is in both cases same: RR does not exist. Same
   for adding, if there is already an RR with exactly same value - is it an
   error?
      #+end_quote
 * Should API have prerequisites?
   - YES
   - can be postponed if needed
----


== API draft

Carsten offered to write a draft specification for the DNS Admin API early
January. He will submit it to our git instane and will request comments: "I will
take comments and pull requests."

== Meeting IRL

We discussed the idea to meet in real life altogether at
link:https://ripe92.ripe.net/[RIPE 92^] in Edinburgh, from May 18 until 22nd
2026, and the overall reaction was to do this.

[NOTE]
Carsten, Pete and Patrick will be there. They've already booked tickets, an
appartment and everything else.


== Next Meeting

Our next meeting will take place on the 28th of January 2026 from 3 p.m. to
4:30 p.m.

Carsten will present his API draft. Please take time to read the draft before
our meeting to allow for a productive atmosphere.


== Next Steps

* Read this protocol draft of our meeting and review it
* Develop a new agenda for the next meeting


