= Minutes from Meeting 01 "Kickoff-Meeting" (May 16th, 2025):Common DNS Admin API
:doctype: article
:keywords: Common DNS Admin API
:author: Patrick Ben Koetter
:email: p@sys4.de
:subject: Kickoff-Meeting
:revnumber: 1.0
:revdate: 2025-05-16
:status: draft
:copyright: (C) sys4 AG
:publisher: sys4 AG
:lang: en
:hyphens: en
:encoding: UTF-8
:pdf-version: 1.7
:toc:
:toclevels: 3
:sectnums:
:pagenums:
:icons: image
:iconsdir: /etc/sys4/corporatedesign/icons
:title-page:
:source-highlighter: rouge
:rouge-style: base16
:pdf-theme: /etc/sys4/corporatedesign/sys4.yml
:pdf-fontsdir: /etc/sys4/corporatedesign/fonts
:asciidoctor-diagram:

== Scope

For now the group limits the scope to develop an API which will manage common
tasks regarding DNS zone administration (Zone maintenance, ACLs, DNSSEC, ...).
Anything managing product (read: software) specific features (think: max MEM
usage) is out of scope.

In other words: We focus on common grounds and leave product specific things
aside for the moment.


== Feature wishlist

Features we said we'd like to see in no particular order:

* audit trail
* capability listing
* idempotence
* input validation
* pull / push model for large platforms
* rollback
* transaction control
* versioning

== API versions

nsupdate (v1)::
    This version implements nsupdate but with better protocol behaviour (Peter
    Eckel said something here about nsupdates bad protocol design and we would
    do it better. But I didn't write it down.)
zones (v2)::
    This version implements zone management, i.e. create, modify, delete a DNS
    zone. It might also bring ACL management because you can't do zone
    management without ACLs (IIRC Colin added this as comment)
dnssec (v3)::
    This version adds DNSSEC management, but what that exactly means hasn't
    been discussed into detail yet.


== Standardization

We don't want the Common DNS Admin API to become an IETF standard as we don't
see the benefit from it. What we see is we need to communicate to others, e.g.
developers of API clients, what the API is, how it behaves etc.

The openapi project and how it publishes information about itself *could* serve
as a best practice example and blueprint. It's not only the way the OpenAPI
project publishes the OpenAPI standard, also (on a more technical level) the
way applications supporting OpenAPI publish details about their particular API
itself. That's what we see as the main benefit from OpenAPI.


== Talking about the project

When asked or when appropriate we agreed to mention our project like this:

* We (company) are looking into a Common DNS Admin API
* We (different vendors) talk to each other about it
* We (project participants) haven't come up with something yet


== Next Steps

* Read the minutes draft of our meeting and review it
* Develop a new agenda for the next meeting
* Find a date for the next meeting


