= Minutes from Meeting 03 (September 25th, 2025):Common DNS Admin API
:doctype: article
:keywords: Common DNS Admin API
:author: Patrick Ben Koetter
:email: p@sys4.de
:subject: Kickoff-Meeting
:revnumber: 0.1
:revdate: 2025-09-25
:status: draft
:copyright: (C) sys4 AG
:publisher: sys4 AG
:lang: en
:hyphens: en
:encoding: UTF-8
:pdf-version: 1.7
:toc:
:toclevels: 3
:sectnums:
:pagenums:
:icons: image
:iconsdir: /etc/sys4/corporatedesign/icons
:title-page:
:source-highlighter: rouge
:rouge-style: base16
:pdf-theme: /etc/sys4/corporatedesign/sys4.yml
:pdf-fontsdir: /etc/sys4/corporatedesign/fonts
:asciidoctor-diagram:

== DNS API examples

Carsten provided a list of link:../assets/dnsapi-survey.adoc[DNS API examples].
We agreed these APIs (only) implement a subset of what NSUPDATE implements,
which means if we implement what NSUPDATE provides we will cover whatever these
APIs cover. We consider that good because it would allow others to adopt our
API.

== Application

We agree we want a layered application. The layers can be provided by separate
applications.

== Authentication

We don't want to reimplement authentication. We want to reuse existing software.
Patrick will have a look into authentication and access control standards and
provide information to the group by at least November 6th.


== Input

We discussed if we should break RDATA into fields as defined by an RTYPE or just
let a user / developer input a STRING and we agreed we don't want to and don't
have to break down an RTYPE into separate fields.

== Working with API data

We agreed to take a look at PowerDNS' API because we just might reuse something
that's already there which has proven to work for what our API will have to
provide.

* Carsten will have a look at the API. He will specifically look for things that
  he believes to be hard to understand. He will deliver his survey by at least
  November 6th.
* Peter (van Dijk) will also have a look at the API. He will specifically look
  for things that could be better from his point of view. He will deliver his
  survey by at least November 6th.


==  Next Meeting

Our next meeting will take place on November 13th from 3 to 4:30 p.m. CEST. An
invitation was sent to the DNS admin mailing list. The invitation also contains
the guest link to the video platform.


== Next Steps

* Read this protocol draft of our meeting and review it
* Develop a new agenda for the next meeting


