openapi: 3.0.0
info:
  title: DNS-API
  version: '1.0'
tags: []
paths:
  /servers/{serverid}:
    get:
      operationId: servers_getZones
      parameters:
        - name: serverid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zone'
  /servers/{serverid}/zones:
    post:
      operationId: zones_createZone
      parameters:
        - name: serverid
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Resource create operation completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zone'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateZone'
  /servers/{serverid}/zones/{zoneid}:
    get:
      operationId: zoneops_getZone
      parameters:
        - name: serverid
          in: path
          required: true
          schema:
            type: string
        - name: zoneid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zone'
    delete:
      operationId: zoneops_deleteZone
      parameters:
        - name: serverid
          in: path
          required: true
          schema:
            type: string
        - name: zoneid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zone'
    patch:
      operationId: zoneops_updateZone
      parameters:
        - name: serverid
          in: path
          required: true
          schema:
            type: string
        - name: zoneid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zone'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RRSetChange'
    put:
      operationId: zoneops_replaceZoneContent
      parameters:
        - name: serverid
          in: path
          required: true
          schema:
            type: string
        - name: zoneid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zone'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateZone'
  /servers/{serverid}/zones/{zoneid}/export:
    get:
      operationId: zoneops_getZoneAXFR
      parameters:
        - name: serverid
          in: path
          required: true
          schema:
            type: string
        - name: zoneid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            text/plain:
              schema:
                type: string
  /servers/{serverid}/zones/{zoneid}/rrsets:
    get:
      operationId: zoneops_getZoneRRSets
      parameters:
        - name: serverid
          in: path
          required: true
          schema:
            type: string
        - name: zoneid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RRSet'
components:
  schemas:
    Comment:
      type: object
      required:
        - text
      properties:
        text:
          type: string
    CreateZone:
      type: object
      required:
        - id
        - name
        - type
        - url
        - kind
        - rrsets
        - serial
        - notified_serial
        - edited_serial
        - primaries
        - dnssec
        - catalog
        - extensions
      properties:
        id:
          type: string
          minLength: 2
        name:
          type: string
        type:
          type: string
        url:
          type: string
        kind:
          type: string
        rrsets:
          type: array
          items:
            $ref: '#/components/schemas/RRSet'
        serial:
          type: integer
          format: int32
        notified_serial:
          type: integer
          format: int32
        edited_serial:
          type: integer
          format: int32
        primaries:
          type: array
          items:
            type: string
        dnssec:
          type: boolean
        catalog:
          type: string
        extensions:
          type: array
          items:
            $ref: '#/components/schemas/Extension'
      description: ''
    Extension:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    RRSet:
      type: object
      required:
        - name
        - type
        - ttl
        - record
        - comments
      properties:
        name:
          type: string
        type:
          type: string
        ttl:
          type: integer
          format: int32
        record:
          type: array
          items:
            $ref: '#/components/schemas/RecordData'
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
    RRSetChange:
      type: object
      required:
        - changetype
      properties:
        changetype:
          $ref: '#/components/schemas/changetype'
      allOf:
        - $ref: '#/components/schemas/RRSet'
    RecordData:
      type: object
      required:
        - data
      properties:
        data:
          type: string
    Server:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
        type:
          $ref: '#/components/schemas/servertype'
    ServerParameters:
      type: object
      required:
        - serverid
      properties:
        serverid:
          type: string
    UpdateZone:
      type: object
      required:
        - type
        - url
        - kind
        - rrsets
        - serial
        - notified_serial
        - edited_serial
        - primaries
        - dnssec
        - catalog
        - extensions
      properties:
        type:
          type: string
        url:
          type: string
        kind:
          type: string
        rrsets:
          type: array
          items:
            $ref: '#/components/schemas/RRSet'
        serial:
          type: integer
          format: int32
        notified_serial:
          type: integer
          format: int32
        edited_serial:
          type: integer
          format: int32
        primaries:
          type: array
          items:
            type: string
        dnssec:
          type: boolean
        catalog:
          type: string
        extensions:
          type: array
          items:
            $ref: '#/components/schemas/Extension'
      description: ''
    Versions:
      type: string
      enum:
        - '1.0'
    Zone:
      type: object
      required:
        - id
        - name
        - type
        - url
        - kind
        - rrsets
        - serial
        - notified_serial
        - edited_serial
        - primaries
        - dnssec
        - catalog
        - extensions
      properties:
        id:
          type: string
          minLength: 2
        name:
          type: string
        type:
          type: string
        url:
          type: string
        kind:
          type: string
        rrsets:
          type: array
          items:
            $ref: '#/components/schemas/RRSet'
        serial:
          type: integer
          format: int32
        notified_serial:
          type: integer
          format: int32
        edited_serial:
          type: integer
          format: int32
        primaries:
          type: array
          items:
            type: string
        dnssec:
          type: boolean
        catalog:
          type: string
        extensions:
          type: array
          items:
            $ref: '#/components/schemas/Extension'
    ZoneParameters:
      type: object
      required:
        - serverid
        - zoneid
      properties:
        serverid:
          type: string
        zoneid:
          type: string
    changetype:
      type: string
      enum:
        - replace
        - add
        - update
        - delete
    servertype:
      type: string
      enum:
        - bind9
        - knot
        - nsd
        - powerdns
        - windows
